# Generated by Django 5.1.4 on 2025-03-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_image',
            field=models.ImageField(default='profile_images/default_profile.png', upload_to='profile_images/'),
        ),
    ]
